## House Price Prediction using Linear Regression

Refer to this link for column description: https://www.kaggle.com/competitions/neolen-house-price-prediction/data

In [4]:
!pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Collecting kagglehub
  Downloading kagglehub-1.0.1-py3-none-any.whl.metadata (40 kB)
     ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
     ---------- ----------------------------- 10.2/40.1 kB ? eta -:--:--
     ---------- ----------------------------- 10.2/40.1 kB ? eta -:--:--
     ------------------- ------------------ 20.5/40.1 kB 131.3 kB/s eta 0:00:01
     ----------------------------- -------- 30.7/40.1 kB 131.3 kB/s eta 0:00:01
     ----------------------------- -------- 30.7/40.1 kB 131.3 kB/s eta 0:00:01
     -------------------------------------- 40.1/40.1 kB 127.6 kB/s eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.28-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python312\site-packages (from kagglehub) (24.1)
Collecting pyyaml (from kagglehub)
  Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in c:\users\user\appdata\roaming\python\python312\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\user\appdata\roaming\python\python312\site-packages (from kagglehub) (4.67.0)
Requirement already satisfied: protobuf in c:\users\user\appdata\roaming\python\python312\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\roaming\python\python312\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\roaming\python\python312\site-packages (from requests->kagglehub) (2024.8.30)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python312\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.1-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
   ----------------- ---------------------- 30.7/70.6 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 70.6/70.6 kB 774.3 kB/s eta 0:00:00
Downloading kagglesdk-0.1.28-py3-none-any.whl (230 kB)
   ---------------------------------------- 0.0/230.0 kB ? eta -:--:--
   ------------------- -------------------- 112.6/230.0 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------  225.3/230.0 kB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 230.0/230.0 kB 2.8 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
   ---------------------------------------- 0.0/154.0 kB ? eta -:--:--
   ---------------------------------------- 154.0/154.0 kB 4.5 MB/s eta 0:00:00
Installing collected packages: pyyaml, kagglesdk, kagglehub
Successfully installed kagglehub-1.0.1 kagglesdk-0.1.28 pyyaml-6.0.3

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

Read csv here. Change your file path.

In [ ]:


train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

print(train_df.head())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12

  YrSold  SaleType  SaleCondition  SalePrice
0   2008        WD         Normal     208500
1   2007        WD         Normal     181500
2   2008        WD         Normal     223500
3   2006        WD        Abnorml     140000
4   2008        WD         Normal     250000

[5 rows x 81 columns]

In [10]:
df = pd.read_csv("train.csv")

Print no. of rows & columns in the dataset

In [12]:
df.shape

(1259, 81)

View 5 row from the top

In [13]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

View 5 rows from the bottom/end

In [14]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1254,1255,60,RL,60.0,6931,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,165400
1255,1256,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,127500
1256,1257,20,RL,91.0,14303,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2008,WD,Normal,301500
1257,1258,30,RL,56.0,4060,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,99900
1258,1259,80,RL,59.0,9587,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,190000


Feature column are the predictor or independent variables. It is represented as X; or $x_1, x_2, .... x_n$

Target column are the response or dependent variables. They depend upon independent or predictor variables $x_1, x_2, .., x_n$. 

In $y = wx + b$, $y$ is the response/target/independent variable and $x$ is the feature/predictor/independent variable.

### Specify the feature and target columns here.

In [15]:
feature_column = ['LotArea', 'TotalBsmtSF', 'PoolArea']
target_column  = 'SalePrice'

In [16]:
print(f"Feature Columns: {feature_column}")
print(f"Target Column: {target_column}")

Feature Columns: ['LotArea', 'TotalBsmtSF', 'PoolArea']
Target Column: SalePrice

Show feature columns

In [67]:
df[feature_column]

      LotArea  TotalBsmtSF  PoolArea Street  LotFrontage
0        8450          856         0   Pave         65.0
1        9600         1262         0   Pave         80.0
2       11250          920         0   Pave         68.0
3        9550          756         0   Pave         60.0
4       14260         1145         0   Pave         84.0
...       ...          ...       ...    ...          ...
1254     6931          746         0   Pave         60.0
1255     6240          884         0   Pave         52.0
1256    14303         1986         0   Pave         91.0
1257     4060          864         0   Pave         56.0
1258     9587          856         0   Pave         59.0

[1259 rows x 5 columns]

Show target column.

In [68]:
df[target_column]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1254    165400
1255    127500
1256    301500
1257     99900
1258    190000
Name: SalePrice, Length: 1259, dtype: int64

### Split the dataset into train set and test set.

`train_test_split()` accepts `test_size` parameter that specify the test set proportion. `.2` means `20%` of the total data is split as test set.

`random_state` parameters helps to create re-producible train and test split. On each invocation of `train_test_split()` with `random_state=42` creates the same train and test split. See more here: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [69]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=.2, random_state=42)

In [70]:
print(f"Train Shape: {train.shape}")
print(f"Test Shape: {test.shape}")

Train Shape: (1007, 81)
Test Shape: (252, 81)

Separate out the feature and target column in train and test set.

In [71]:
train_x = train[feature_column]
train_y = train[target_column]

test_x = test[feature_column]
test_y = test[target_column]

In [35]:
## TODO : Write code here to to print train_x, train_y, test_x, test_y
## See how the columns are different in feature and target dataframes

In [72]:
print("Train Features (train_x):")
print(train_x.head())

print("\nTest Features (test_x):")
print(test_x.head())

# Print target data
print("\nTrain Target (train_y):")
print(train_y.head())

print("\nTest Target (test_y):")
print(test_y.head())

Train Features (train_x):
     LotArea  TotalBsmtSF  PoolArea Street  LotFrontage
243    10762          626         0   Pave         75.0
514    10594          768         0   Pave         55.0
966     9600          728         0   Pave        130.0
199     9591         1713         0   Pave         76.0
270    10728         1095         0   Pave         84.0

Test Features (test_x):
      LotArea  TotalBsmtSF  PoolArea Street  LotFrontage
76       8475          952         0   Pave          NaN
1026     9300         1268         0   Pave         73.0
43       9200          938         0   Pave          NaN
666     18450         1021         0   Pave          NaN
529     32668         2035         0   Pave          NaN

Train Target (train_y):
243    120000
514     96500
966    160000
199    274900
270    266000
Name: SalePrice, dtype: int64

Test Target (test_y):
76      135750
1026    167500
43      130250
666     129000
529     200624
Name: SalePrice, dtype: int64

In [73]:
print("Feature Columns:")
print(train_x.columns)

print("\nTarget Column:")
print(train_y.name)  # if target_column is a single column

Feature Columns:
Index(['LotArea', 'TotalBsmtSF', 'PoolArea', 'Street', 'LotFrontage'], dtype='object')

Target Column:
SalePrice

Print shape of each dataframe here

In [74]:
train_x.shape, train_y.shape, test_x.shape, test_y.shape

((1007, 5), (1007,), (252, 5), (252,))

In [75]:
test_y

76      135750
1026    167500
43      130250
666     129000
529     200624
         ...
430      85400
32      179900
156     109500
376     148000
620      67000
Name: SalePrice, Length: 252, dtype: int64

In [ ]:
# convert categorical data into numeric
train_x = pd.get_dummies(train_x)
test_x = pd.get_dummies(test_x)

In [80]:
test_x = test_x.reindex(columns=train_x.columns, fill_value=0)

In [84]:
train_x = train_x.fillna(0)
test_x = test_x.fillna(0)

In [81]:
print(train_x.select_dtypes(include='object').columns)

Index([], dtype='object')

## Linear Regression model 

Import LinearRegression model

In [82]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()

Call `.fit()` method to learn the model parameters. 

In $y = wx + b$, `w` and `b` are the model parameters. `.fit()` computes these parameters.

In [85]:
model.fit(train_x, train_y)

LinearRegression()

Print learned `w` here.

See how no. of values change on changing the no. of feature columns.

In [86]:
model.coef_

array([ 9.29004357e-01,  1.13162277e+02,  1.44662261e+02,  2.14639167e+02,
       -4.06413855e+04,  4.06413855e+04])

Print bias/intercept `b` here.

In [87]:
model.intercept_

np.float64(-739.7171481443511)

Use the learned linear regression model to predict on the test data set.

In [88]:
y_pred = model.predict(test_x)

In [89]:
print(y_pred)

[155505.46769    207699.83493716 154594.72397518 172580.48323864
 300535.61572919 148834.54539054 145928.07912899 156243.69546324
 171540.000327   151269.27362834 125383.84298443 254520.24404068
 273262.2409327  168893.57431011 184130.22225378 187052.99760827
 169859.34837074 313273.79588319 148318.77451417 234012.83290241
 231051.81090886 186343.72020204 227317.708015   268196.93463588
 140140.34141023 139983.41331486 211425.27824074 190932.37758251
 172296.76079267 148800.16036011 194445.95621453 160038.99511274
 179219.76481779 239068.08294088 195943.36316241 140841.29288124
 160944.9460546  108255.29661281  41986.19774114 241485.42559398
 153430.30793174 224809.18196472 149457.50110935 228791.94353735
 172755.40010308 265439.40254564 196620.53277235 143162.40966055
 165197.72813729 166185.59762394 122014.86813411 159101.77290721
 149200.31003273 168624.31631905 120552.50380697 156895.34484652
 140798.58800073 130927.05642814 151954.17414818 201000.3895415
 170958.67388483 157260.84005398 205787.67352802 178000.01547439
 153402.30559199 194144.22732033 186264.80979864 158338.65285374
 226337.30114372 292732.96755593 150214.09471694 187395.2343786
 154950.58390348 214387.901314   169330.17937845 243262.84367451
 159821.82007713 250943.15614483 260923.75716369 256755.39995904
 179638.45077259 213054.9502462  178858.11039646 172602.56717871
 192250.68223105 241572.77041374 218640.92966832 253751.81425875
 167913.01810308 215474.98811061 218656.33709657 152372.17069738
 285557.66851192  64172.13558083 136191.63966161 197070.07662114
 152766.63284609 143422.98006224 204054.75111637 259681.66367309
 192443.967884   192117.81632969 185502.64424175 117499.42584298
 186802.35735248 166129.77408402 134075.11796169 129586.83725233
 155924.32107826 154556.01494044 226229.02736401 167050.00364767
 155802.74908415 126427.28250257 233439.16722147 194720.09469829
 144753.37338524 102254.77545493 146952.05582161 187237.098003
 167060.57767776 211262.14800655 186468.28999268 136450.01659993
 263500.26693425 118383.16979164 168055.45566447 324533.9688003
 135991.77512854 264121.31836691 171713.92743607 147057.0733514
 158599.0041552   60128.83449306 145492.68918203 154506.67629601
 194244.12496221 307789.09258725 166645.97611616 184174.64106471
 238703.60877746 182774.71312142 124239.01118631  93400.71525261
  93271.66102104 157689.08534373 299605.94744473 199058.81054221
 148047.26132243 153875.59836928 318798.01929067 122089.6596759
 249511.90938837 102861.84974432 159774.96239414 160277.23887811
 157277.63328938 282026.74933785 133695.60322142 183397.20239983
 149528.4626428  124110.19902597 201766.43261893 145172.42988724
  66726.62343441 133527.43134974 110691.63799164 176466.15800406
 145047.64836503 202263.15201137 162373.97480356 122014.86813411
 157678.0755971  205815.47885064 158166.86416945 165999.12479767
 163344.71207061 132874.50903296 174035.88139505 106120.79335478
 228237.40137377 132859.14341886 168724.11722859 157988.24836553
 208522.90099337 162103.95791764 199133.83825072 179064.85285389
 240502.39196651 222910.62017772 255066.7924121   93374.36559913
 192942.62551581 285274.08594473 138541.48575128 189473.65457481
 185189.03874008 183020.02663101 148767.30736362 117086.47069041
 316853.47990889 325911.81078601 146454.63367872  47839.0815975
 221199.47741972 192037.25502816 178300.29288839 179621.46066339
 161419.05772177 224352.68094721 139877.49557309 134852.18064128
 187507.08981817 165676.77366804 172784.74024463 214298.05586196
 160176.37307082 147925.06251062 200533.02906975 157319.49832564
 215292.39404258 171706.1856767  160139.62875015 185170.26398787
 162453.16288679 156569.22515626 251053.68676911 178670.82274884
 158212.86152114 114957.0238072  144613.11296529 156530.81017204
 194468.80812314 136316.55947801 224276.3473497  262324.28933697
  77507.82051359 155429.06534777 200721.58147744 245880.51950979
 123592.19362807 254356.41488371 189003.68277238 156625.47457157
 158776.16250274 145368.82192683 161690.77496388 100627.19784283
 208052.81615959  59468.84978927 158805.25416394 154995.06588915]

Import `root_mean_squared_error` from `sklearn.metrics` and calculate the RMSE for the predictions.

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html

In [ ]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(test_y, y_pred)
print(f"Mean Squared Error: {MSE}")

# calculate RMSE
RMSE = np.sqrt(MSE)

print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 3434073944.511251
Root Mean Squared Error: 58600.972214727386

Assignement: Add/remove features from `feature_column` and run all the code to see how `MSE` and `RMSE` changes. Document the RMSE and MSE and corresponding features.

In [38]:
feature_column = ['LotArea', 'TotalBsmtSF', 'PoolArea', 'Street', 'LotFrontage']
target_column  = 'SalePrice'

In [39]:
print(f"Feature Columns: {feature_column}")
print(f"Target Column: {target_column}")

Feature Columns: ['LotArea', 'TotalBsmtSF', 'PoolArea', 'Street', 'LotFrontage']
Target Column: SalePrice