In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("./test.csv")

In [3]:
df.tail()

   name  id address
0   ram   1     ktm
1  lisa   2     pkr

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     2 non-null      object
 1   id       2 non-null      int64
 2   address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [5]:
df["id"]==1

0     True
1    False
Name: id, dtype: bool

In [8]:
df[df["id"]==1]

  name  id address
0  ram   1     ktm

In [6]:
df[["id","address"]]

   id address
0   1     ktm
1   2     pkr

In [ ]:
model.fit()
model.transform()
model.predict()